spring.application.name=backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://admin1234:yvqB8IfwQOfQluMo@chatgptloginsystem.rm5au8p.mongodb.net/interntrackdb?retryWrites=true&w=majority&appName=chatgptloginsystemspring.application.name=backend

jwt.secret=InternTrackProSecretKeyForJWTAuthentication2026InternTrack
jwt.expiration=86400000